# Directory of the source code and metadata
RAW_DIR = "data/raw"

# Metadata of the cases from API
CASE_METADATA_PATH = "data/raw/case_metadata.json"

# Case transformed data generated by the model
CASE_TRANSFORMED_PATH = "data/transformed/case_{model}.jsonl"

# Statistics of the transformed data
CASE_STATS_PATH = "data/transformed/case_{model}_stats.json"
