# Directory of the source code and metadata
RAW_DIR = "data/raw"

# Metadata of the cases from API
CASE_METADATA_PATH = "data/raw/case_metadata.json"

# Case converted data generated by the model
CASE_CONVERTED_PATH = "data/conversion/case_{model}.jsonl"

# Statistics of the converted data
CASE_STATS_PATH = "data/conversion/case_{model}_stats.json"
